### ISSUE TITLE
Failed to build (mkdir /app)

### ISSUE THREAD

**Issue by f0m3** [okainov/ebay-kleinanzeigen#1]
Hey, my build fails on a raspberry on:
```
pi@raspberrypi:~/ebay-kleinanzeigen $ sudo docker-compose build
/usr/local/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
Building tg-bot
Step 1/7 : FROM python:3.8
 ---> 94ebb02c00ed
Step 2/7 : RUN mkdir ../app
 ---> Running in 877ddebe3f7f
ERROR: Service 'tg-bot' failed to build: The command '/bin/sh -c mkdir ../app' returned a non-zero code: 139
```
i tried with and without sudo. freshly after dist-upgrade. Any ideas?

**Comment by okainov** [comment]
Sorry for the delay. I've just checked - it builds perfectly.

> Step 2/7 : RUN mkdir ../app

This is not part of the `Dockerfile` in the repository. Please undo your changes and try to build code from repository "as is". Original code there is `RUN mkdir /app` (because commands from Dockerfile are executed inside the containers and don't affect your host filesystem, so there is nothing wrong in creating very top-level paths like `/app`)
